import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "./../globals.css";
import { NextAuthProvider } from "../../components/NextAuthProviders";
import Navbar from "@/components/Navbar";
import SignInBtn from "@/components/SignInBtn";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Navbar />
      {children}
    </>
  );
}
