"use client";

// import type { Metadata } from "next";

// import { Inter } from "next/font/google";
import "./../globals.css";
// import { NextAuthProvider } from "../../components/NextAuthProviders";
// import Navbar from "@/components/Navbar";
// import SignInBtn from "@/components/SignInBtn";
import { useSession } from "next-auth/react";
import { redirect } from "next/navigation";
import LoadingPage from "@/components/Loading";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { status } = useSession();

  if (status === "loading") return <LoadingPage />;

  if (status === "authenticated") {
    redirect("/home");
  }

  return (
    <main className="w-screen h-screen flex flex-col justify-center items-center px-4 md:px-12 lg:px-24">
      <div className="w-full max-w-[400px]">{children}</div>
    </main>
  );
}
